//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 12/07/2018 12:48:28 p.m.
namespace MSS_YAMBOLY_GEOLOCATION.Services.ODataService
{
    
    /// <summary>
    /// There are no comments for ODataService in the schema.
    /// </summary>
    public partial class ODataService : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new ODataService object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public ODataService(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for OCRD in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<OCRDType> OCRD
        {
            get
            {
                if ((this._OCRD == null))
                {
                    this._OCRD = base.CreateQuery<OCRDType>("OCRD");
                }
                return this._OCRD;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<OCRDType> _OCRD;
        /// <summary>
        /// There are no comments for CRD1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<CRD1Type> CRD1
        {
            get
            {
                if ((this._CRD1 == null))
                {
                    this._CRD1 = base.CreateQuery<CRD1Type>("CRD1");
                }
                return this._CRD1;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<CRD1Type> _CRD1;
        /// <summary>
        /// There are no comments for OCRD in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToOCRD(OCRDType oCRDType)
        {
            base.AddObject("OCRD", oCRDType);
        }
        /// <summary>
        /// There are no comments for CRD1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToCRD1(CRD1Type cRD1Type)
        {
            base.AddObject("CRD1", cRD1Type);
        }
    }
    /// <summary>
    /// There are no comments for MSS_YAMBOLY_GEOLOCATION.Services.ODataService.OCRDType in the schema.
    /// </summary>
    /// <KeyProperties>
    /// CardCode
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("OCRD")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("CardCode")]
    public partial class OCRDType : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new OCRDType object.
        /// </summary>
        /// <param name="cardCode">Initial value of CardCode.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static OCRDType CreateOCRDType(string cardCode)
        {
            OCRDType oCRDType = new OCRDType();
            oCRDType.CardCode = cardCode;
            return oCRDType;
        }
        /// <summary>
        /// There are no comments for Property CardCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CardCode
        {
            get
            {
                return this._CardCode;
            }
            set
            {
                this.OnCardCodeChanging(value);
                this._CardCode = value;
                this.OnCardCodeChanged();
                this.OnPropertyChanged("CardCode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CardCode;
        partial void OnCardCodeChanging(string value);
        partial void OnCardCodeChanged();
        /// <summary>
        /// There are no comments for Property CardName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CardName
        {
            get
            {
                return this._CardName;
            }
            set
            {
                this.OnCardNameChanging(value);
                this._CardName = value;
                this.OnCardNameChanged();
                this.OnPropertyChanged("CardName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CardName;
        partial void OnCardNameChanging(string value);
        partial void OnCardNameChanged();
        /// <summary>
        /// There are no comments for Property LicTradNum in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string LicTradNum
        {
            get
            {
                return this._LicTradNum;
            }
            set
            {
                this.OnLicTradNumChanging(value);
                this._LicTradNum = value;
                this.OnLicTradNumChanged();
                this.OnPropertyChanged("LicTradNum");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _LicTradNum;
        partial void OnLicTradNumChanging(string value);
        partial void OnLicTradNumChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for MSS_YAMBOLY_GEOLOCATION.Services.ODataService.CRD1Type in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Address
    /// CardCode
    /// AdresType
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("CRD1")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Address", "CardCode", "AdresType")]
    public partial class CRD1Type : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new CRD1Type object.
        /// </summary>
        /// <param name="address">Initial value of Address.</param>
        /// <param name="cardCode">Initial value of CardCode.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static CRD1Type CreateCRD1Type(string address, string cardCode)
        {
            CRD1Type cRD1Type = new CRD1Type();
            cRD1Type.Address = address;
            cRD1Type.CardCode = cardCode;
            return cRD1Type;
        }
        /// <summary>
        /// There are no comments for Property Address in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Address
        {
            get
            {
                return this._Address;
            }
            set
            {
                this.OnAddressChanging(value);
                this._Address = value;
                this.OnAddressChanged();
                this.OnPropertyChanged("Address");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Address;
        partial void OnAddressChanging(string value);
        partial void OnAddressChanged();
        /// <summary>
        /// There are no comments for Property CardCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CardCode
        {
            get
            {
                return this._CardCode;
            }
            set
            {
                this.OnCardCodeChanging(value);
                this._CardCode = value;
                this.OnCardCodeChanged();
                this.OnPropertyChanged("CardCode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CardCode;
        partial void OnCardCodeChanging(string value);
        partial void OnCardCodeChanged();
        /// <summary>
        /// There are no comments for Property AdresType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string AdresType
        {
            get
            {
                return this._AdresType;
            }
            set
            {
                this.OnAdresTypeChanging(value);
                this._AdresType = value;
                this.OnAdresTypeChanged();
                this.OnPropertyChanged("AdresType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _AdresType = "S";
        partial void OnAdresTypeChanging(string value);
        partial void OnAdresTypeChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
