//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YAMBOLY.GESTIONRUTAS.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config
    {
        public int ConfigId { get; set; }
        public string C_Key { get; set; }
        public string C_Name { get; set; }
        public string C_Description { get; set; }
        public string C_Value { get; set; }
    }
}
